### ISSUE TITLE
Compilation error MacOS

### ISSUE THREAD

**Issue by nextgenusfs** [xiaochuanle/MECAT#5]
Trying to build on Mac OS Sierra using gcc-6 and getting the following error at the dextractor build step.  Same error if I use default clang to build.
```
echo /usr/local/MECAT
/usr/local/MECAT
cd aux_tools/dextractor && make PATH_HDF5=/usr/local/MECAT/aux_tools/hdf5 BUILD_DIR=/usr/local/MECAT/Darwin-amd64/bin
gcc-6 -O3 -Wall -Wextra -Wno-unused-result -fno-strict-aliasing -I/usr/local/MECAT/aux_tools/hdf5/include -L/usr/local/MECAT/aux_tools/hdf5/lib -o /usr/local/MECAT/Darwin-amd64/bin/dextract DEXTRACTOR/dextract.c DEXTRACTOR/DB.c DEXTRACTOR/QV.c -lhdf5
ld: can't open output file for writing: /usr/local/MECAT/Darwin-amd64/bin/dextract, errno=2 for architecture x86_64
collect2: error: ld returned 1 exit status
make[1]: *** [dextract] Error 1
make: *** [dextract] Error 2
```

**Comment by xiaochuanle** [comment]
please run
mkdir -p /usr/local/MECAT/Darwin-amd64/bin/
before running
cd aux_tools/dextractor && make PATH_HDF5=/usr/local/MECAT/aux_tools/hdf5 BUILD_DIR=/usr/local/MECAT/Darwin-amd64/bin
gcc-6 -O3 -Wall -Wextra -Wno-unused-result -fno-strict-aliasing -I/usr/local/MECAT/aux_tools/hdf5/include -L/usr/local/MECAT/aux_tools/hdf5/lib -o /usr/local/MECAT/Darwin-amd64/bin/dextract DEXTRACTOR/dextract.c DEXTRACTOR/DB.c DEXTRACTOR/QV.c -lhdf5

**Comment by nextgenusfs** [comment]
Thanks that fixed it!
